# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ffe1fc95e9653143396becbe9eea9a52bce1efd61c5bc40c6b0cc71fa44685e7dfadcb4da3ee43545299440af124588dcba4c1c1bfdbb15c04527f912c06fd8

test:
  secret_key_base: ac75c041dfbdd45dba646e874c7641f3e30495d71c3f0641541191b5fb153e1e36568cd0fe0ec75581b0032ba1adcee141daa9f1b8bc57ecfb19d1df7a3c6773

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
